#!/usr/bin/env bash
# Bash script configure your Nginx server so
# that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=RMS5zBYQIqA permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
