#!/usr/bin/env bash
# Bash script configure your Nginx server so
# that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "35i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart
