#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo-e "backend backendnodes\n\tbalance roundrobin\n\tserver 2357-web-01 35.231.81.64:80 check\n\tserver 2357-web-02 34.74.73.209:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
