#!/usr/bin/env bash
# displays numbers from 1 to 20 and
#displays 4 and then bad luck from China for the 4th
#displays 9 and then bad luck from Japan for the 9th
#displays 17 and then bad luck from Italy for the 17th

i=1
while [ "$i" -le 20 ]; do
	echo "$i"
	case "$i" in 
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	let i=i+1
done
